add `set -e -o pipefail` to all scripts
- fixes false successes (e.g. golint not downloaded)

Signed-off-by: Adrian Zankich <azankich@pivotal.io>

diff --git a/bin/golint b/bin/golint
--- a/bin/golint
+++ b/bin/golint
@@ -1,9 +1,13 @@
 #!/bin/bash
 
+set -e -o pipefail
+
 bin=$(dirname $0)
 
 go get -u github.com/golang/lint/golint
 
+
+set +e # golint will fail on the issues we filter out
 errors=$(
   $bin/gofiles $bin/env golint                              \
     | grep -v 'should have comment.* or be unexported'      \
@@ -16,6 +20,7 @@ errors=$(
     | grep -v 'platform/cert/fakes/fake_manager.go'         \
     | grep -v 'jobsupervisor/pipe/syslog/syslog.go'
 )
+set -e
 
 if [ "$(echo -n "$errors")" != "" ]; then
   echo "$errors"
