Fix govet and moved test unhandled errors in to bin/test-unit
[#97657552](https://www.pivotaltracker.com/story/show/97657552)

Signed-off-by: Kam Leung <kleung@pivotal.io>

diff --git a/bin/test-unit b/bin/test-unit
--- a/bin/test-unit
+++ b/bin/test-unit
@@ -28,6 +28,14 @@ echo -e "\n Installing ginkgo..."
 $bin/go install ./internal/github.com/onsi/ginkgo/ginkgo
 let "result+=$?"
 
+echo -e "\n Govetting"
+$bin/govet
+let "result+=$?"
+
+echo -e "\n Checking for unhandled errors"
+$bin/test-unhandled-errors
+let "result+=$?"
+
 echo -e "\n Testing packages..."
 $bin/env ginkgo -r $race -skipPackage="integration,internal" $bin/..
 let "result+=$?"
