Harmonize CI scripts with bosh-cli

diff --git a/bin/test-unit b/bin/test-unit
--- a/bin/test-unit
+++ b/bin/test-unit
@@ -6,13 +6,23 @@ ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 echo 'Note: if you want to quickly run tests for just one package, do it like this:'
 echo '  % bin/ginkgo path/to/package'
 
-"${ROOT_DIR}/bin/format" # TODO: this should be called in parallel via Concourse
+echo -e "\n Checking formatting..." # TODO: should CI do this in parallel?
+files_needing_reformat="$("${ROOT_DIR}/bin/format" -l)"
+if [[ ${files_needing_reformat} = *[![:space:]]* ]]; then
+  echo "Error: some files require formatting (below)"
+  echo "${files_needing_reformat}"
+  echo "Error: some files require formatting (above)"
+  echo "=> run 'bin/format -w' to reformat with 'goimports'"
+  echo "   see: https://pkg.go.dev/golang.org/x/tools/cmd/goimports"
+  exit 1
+fi
 
-"${ROOT_DIR}/bin/lint" # TODO: this should be called in parallel via Concourse
+echo -e "\n Running linter..." # TODO: should CI do this in parallel?
+"${ROOT_DIR}/bin/lint"
 
 for os in windows linux; do
   echo -e "\n build-ing with GOOS=${os} to confirm everything compiles..."
-  GOOS="${os}" "${ROOT_DIR}/bin/build" # TODO: this should be called in parallel via Concourse
+  GOOS="${os}" "${ROOT_DIR}/bin/build" # TODO: should CI do this in parallel?
 done
 
 echo -e "\n Testing packages..."
