Make tests better

diff --git a/bin/test-integration b/bin/test-integration
--- a/bin/test-integration
+++ b/bin/test-integration
@@ -10,21 +10,21 @@ if [ ! -d "${base}"/tmp ]; then
   mkdir -p "${base}"/tmp
 fi
 
-cleanup() {
-	echo "Cleaning up"
+# cleanup() {
+# 	echo "Cleaning up"
 
-  (cd $base && vagrant destroy -f)
+#   (cd $base && vagrant destroy -f)
 
-  if [ ! -z "$OLD_BOSH_LITE_PRIVATE_KEY" ]; then
-    export BOSH_LITE_PRIVATE_KEY=$OLD_BOSH_LITE_PRIVATE_KEY
-  fi
+#   if [ ! -z "$OLD_BOSH_LITE_PRIVATE_KEY" ]; then
+#     export BOSH_LITE_PRIVATE_KEY=$OLD_BOSH_LITE_PRIVATE_KEY
+#   fi
 
-  if [ -f "$tmpfile" ]; then
-    rm -rf $tmpfile
-  fi
-}
+#   if [ -f "$tmpfile" ]; then
+#     rm -rf $tmpfile
+#   fi
+# }
 
-trap cleanup EXIT
+# trap cleanup EXIT
 
 # Vagrant needs ubuntu to own the private key if aws provider
 if [ ! -z "$BOSH_LITE_PRIVATE_KEY" ]; then
